language: generic
sudo: require
services:
    - docker

before_install:
    - docker build -t roaslin/single-client -f Dockerfile.dev .
scripts:
    - docker run -e CI=true roaslin/single-client npm run test
 